/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TagLibReader */

#ifndef _Included_TagLibReader
#define _Included_TagLibReader
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     TagLibReader
 * Method:    getTags
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_TagLibReader_getTags
  (JNIEnv *, jobject, jstring);

/*
 * Class:     TagLibReader
 * Method:    getArtist
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TagLibReader_getArtist
  (JNIEnv *, jobject, jstring);

/*
 * Class:     TagLibReader
 * Method:    getAlbum
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TagLibReader_getAlbum
  (JNIEnv *, jobject, jstring);

/*
 * Class:     TagLibReader
 * Method:    getTitle
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_TagLibReader_getTitle
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
