/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChromaPrint */

#ifndef _Included_ChromaPrint
#define _Included_ChromaPrint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChromaPrint
 * Method:    getFingerprint
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ChromaPrint_getFingerprint
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
