/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ChromaPrint */

#ifndef _Included_ChromaPrint
#define _Included_ChromaPrint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ChromaPrint
 * Method:    getFingerprint
 * Signature: (Ljava/lang/String;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_ChromaPrint_getFingerprint
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ChromaPrint
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ChromaPrint_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
